### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by madmast** [jkgaurav/github-crash-course#1]
I think it looks better if the main title is a bit more blue

The styling rule could be changed like this:

```css
h1 {
  color: #bfb2e8;
}
```
